{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if and $isDistributed .Values.overridesExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.overridesExporterFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.overridesExporterLabels" . | nindent 4 }}
  {{- with .Values.loki.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.overridesExporter.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.loki.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "loki.overridesExporterSelectorLabels" . | nindent 6 }}
  template:
    {{- include "loki.podTemplate" (dict "target" "overrides-exporter" "component" .Values.overridesExporter "ctx" .) | nindent 4 }}
{{- end -}}
