{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if and $isDistributed .Values.ruler.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "loki.rulerFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.rulerLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
  {{- with .Values.loki.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.ruler.replicas }}
  revisionHistoryLimit: {{ .Values.loki.revisionHistoryLimit }}
  serviceName: {{ include "loki.rulerFullname" . }}
  selector:
    matchLabels:
      {{- include "loki.rulerSelectorLabels" . | nindent 6 }}
  template:
    {{- include "loki.podTemplate" (dict "target" "ruler" "component" .Values.ruler "ctx" .) | nindent 4 }}
  {{- if .Values.ruler.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        {{- with .Values.ruler.persistence.annotations }}
        annotations:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.ruler.persistence.labels }}
        labels:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.ruler.persistence.accessModes | nindent 10 }}
        {{- with .Values.ruler.persistence.storageClass }}
        storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
        {{- end }}
        {{- with .Values.ruler.persistence.volumeAttributesClassName }}
        volumeAttributesClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.ruler.persistence.size | quote }}
  {{- end }}
{{- end }}
