{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.service" (dict "target" "ingester" "component" .Values.ingester "ctx" .) }}
{{- end -}}
