{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.querySchedulerFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.querySchedulerLabels" . | nindent 4 }}
  {{- with .Values.loki.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.queryScheduler.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.loki.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "loki.querySchedulerSelectorLabels" . | nindent 6 }}
  template:
    {{- include "loki.podTemplate" (dict "target" "query-scheduler" "component" .Values.queryScheduler "ctx" .) | nindent 4 }}
{{- end }}
