#!/usr/bin/env bash

set -euf -o pipefail

function usage {
  cat <<EOF
Create the POD Disruption Budget manifest template

Usage:
  $0 <component>

Examples:
  $0 overrides-exporter
EOF
}

if [[ $# -eq 0 ]]; then
  usage
  exit 1
fi

case "$1" in
  -h) usage && exit 0 ;;
  *) ;; # default
esac

# Convert kebab-case to camelCase.
# Only works with GNU sed.
function camel_case {
  sed -E -e 's/-(.)/\U\1/' <<<"$1"
}
# Convert kebab-case to snake_case.
function snake_case {
  sed -E -e 's/-/_/' <<<"$1"
}

component="$1"
camel_cased="$(camel_case "$1")"
snake_cased="$(snake_case "$1")"

cat <<EOF
{{- if .Values.${snake_cased}.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "mimir.${camel_cased}Fullname" . }}
  labels:
    {{- include "mimir.${camel_cased}Labels" . | nindent 4 }}
    {{- if .Values.useGEMLabels }}{{- include "mimir.gemExtraLabels" . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mimir.${camel_cased}SelectorLabels" . | nindent 6 }}
{{ toYaml .Values.${snake_cased}.podDisruptionBudget | indent 2 }}
{{- end -}}
EOF
