#!/usr/bin/env bash

set -euf -o pipefail

function usage {
  cat <<EOF
Create a helper template file for a component.

Usage:
  $0 [options] <component>
 
Options:
  -g  Add gossip_ring_member: true Pod label

Examples:
  $0 overrides-exporter
  $0 -g distributor
EOF
}

if [[ $# -eq 0 ]]; then
  usage
  exit 1
fi

# Convert kebab-case to camelCase.
# Only works with GNU sed.
function camel_case {
  sed -E -e 's/-(.)/\U\1/' <<<"$1"
}

GOSSIP_RING_MEMBER=''
case "$1" in
  -g)
    shift
    GOSSIP_RING_MEMBER=$'gossip_ring_member: "true"\n'
    ;;
  -h) usage && exit 0 ;;
  *) ;; # default
esac

component="$1"
camel_cased="$(camel_case "$1")"

cat <<EOF
{{/*
${component} fullname
*/}}
{{- define "mimir.${camel_cased}Fullname" -}}
{{ include "mimir.fullname" . }}-${component}
{{- end }}

{{/*
${component} common labels
*/}}
{{- define "mimir.${camel_cased}Labels" -}}
{{ include "mimir.labels" . }}
{{- if .Values.useGEMLabels }}
app: {{ template "mimir.name" . }}-${component}
{{- else }}
app.kubernetes.io/component: ${component}
app.kubernetes.io/part-of: memberlist
{{- end }}
{{- end -}}

{{/*
${component} selector labels
*/}}
{{- define "mimir.${camel_cased}SelectorLabels" -}}
{{ include "mimir.selectorLabels" . }}
{{- if .Values.useGEMLabels }}
app: {{ template "mimir.name" . }}-${component}
{{- else }}
app.kubernetes.io/component: ${component}
{{- end }}
{{- end -}}

{{/*
GEM ${component} Pod labels
*/}}
{{- define "mimir.gem${camel_cased^}PodLabels" -}}
name: ${component}
target: ${component}
${GOSSIP_RING_MEMBER}{{- end -}}
EOF
