traces:
  otlp:
    http:
      enabled: true

gateway:
  enabled: true
  route:
    main:
      enabled: true
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      annotations:
        test-annotation: test-value
      labels:
        test-label: test-value
      hostnames:
        - tempo.example.com
      parentRefs:
        - name: my-gateway
          namespace: default
      paths:
        distributor:
          - path: /v1/traces
            pathType: PathPrefix
            port: 4318
          - path: /distributor/ring
            pathType: PathPrefix
        ingester:
          - path: /flush
            pathType: PathPrefix
        query-frontend:
          - path: /api
            pathType: PathPrefix
        compactor:
          - path: /compactor/ring
            pathType: PathPrefix
