{{- $isSimpleScalable := eq (include "loki.deployment.isScalable" .) "true" -}}
{{- if $isSimpleScalable }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "loki.writeFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.writeLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
  {{- if or (not (empty .Values.loki.annotations)) (not (empty .Values.write.annotations))}}
  annotations:
    {{- with .Values.loki.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.write.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
{{- if not .Values.write.autoscaling.enabled }}
  {{- if eq .Values.deploymentMode "SingleBinary" }}
  replicas: 0
  {{- else }}
  replicas: {{ .Values.write.replicas }}
  {{- end }}
{{- end }}
  podManagementPolicy: {{ .Values.write.podManagementPolicy }}
  updateStrategy:
    rollingUpdate:
      partition: 0
  serviceName: {{ include "loki.writeFullname" . }}-headless
  revisionHistoryLimit: {{ .Values.loki.revisionHistoryLimit }}
  {{- if and (.Values.write.persistence.enableStatefulSetAutoDeletePVC) (.Values.write.persistence.volumeClaimsEnabled) }}
  {{/*
    Data on the write nodes is easy to replace, so we want to always delete PVCs to make
    operation easier, and will rely on re-fetching data when needed.
  */}}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  {{- end }}
  selector:
    matchLabels:
      {{- include "loki.writeSelectorLabels" . | nindent 6 }}
  template:
    {{- include "loki.podTemplate" (dict "target" "write" "component" .Values.write "ctx" .) | nindent 4 }}
  {{- if .Values.write.persistence.volumeClaimsEnabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        {{- with .Values.write.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.write.persistence.labels }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.write.persistence.accessModes | nindent 10 }}
        {{- with .Values.write.persistence.storageClass }}
        storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
        {{- end }}
        {{- with .Values.write.persistence.volumeAttributesClassName }}
        volumeAttributesClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.write.persistence.size | quote }}
        {{- with .Values.write.persistence.selector }}
        selector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- with .Values.write.extraVolumeClaimTemplates }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
