on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'
permissions: {}
jobs:
  build:
    permissions:
      contents: write # for git push

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6 # zizmor: ignore[artipacked] without this ignore comment, zizmor would complain that persist-credentials is not explicitly set to false. We need it set to true (default) to be able to push the push the commit later on in this workflow
        with:
          ref: gh-pages
      - run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README from main"
          git push
